#!/usr/bin/env python3
"""Builds docs/patch.js (the Open500 patch for the Akai MPC500 OS 1.31) and copies the add-ons into docs/addons.

The patch holds ONLY Open500 data: the loader code (written into a region of the original OS that is all zeros) and
the 4-byte pointer that hooks it into the OS main loop. The OS CRC is recomputed by the browser patcher.
Usage: python3 tools/make_patch.py   (from the open500/ folder)
"""
import os, json, shutil, zlib, hashlib, struct, glob, zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RE = os.path.join(ROOT, '..', 're_work')
ORIG = os.path.join(RE, 'mpc500.bin')                                   # official OS 1.31 (checked against the Akai zip below)
PATCHED = os.path.join(RE, 'release', 'v4_topmem', 'mpc500_loader.bin')  # loader v8, tested on the hardware
ADDONS = [(n, 'release/v8_chops/' + n) for n in ('HUB.WAV', 'CHOPAGE.WAV', 'SAMPLEFX.WAV', 'AUTOWARP.WAV', 'TRANSCHP.WAV')]
CRC_OFF, OS_HDR = 0x10010, 0x10000

def main():
    o = open(ORIG, 'rb').read(); p = open(PATCHED, 'rb').read()
    zips = glob.glob(os.path.join(RE, '..', 'mpc500_v131_00.zip*'))
    for z in zips:                                  # the base must be exactly the file Akai distributes
        zf = zipfile.ZipFile(z); assert zf.read('mpc500.bin') == o, 'mpc500.bin differs from the Akai zip'
        print('base identical to Akai', os.path.basename(z))
    assert len(o) == len(p) == 514732
    diff = [i for i in range(len(o)) if o[i] != p[i] and not (CRC_OFF <= i < CRC_OFF + 4)]
    # group into blocks (gaps < 16 bytes merged: some loader bytes happen to be zero like the original)
    blocks = []
    for i in diff:
        if blocks and i - blocks[-1][1] < 16: blocks[-1][1] = i + 1
        else: blocks.append([i, i + 1])
    patches = []
    for a, b in blocks:
        patches.append({'off': a, 'orig': o[a:b].hex(), 'data': p[a:b].hex()})
    size = struct.unpack('<I', o[OS_HDR + 0xC:OS_HDR + 0x10])[0]
    out = {
        'name': 'Open500 loader v8',
        'target': 'Akai MPC500 OS 1.31 (mpc500.bin)',
        'size': len(o),
        'base_crc32': zlib.crc32(o) & 0xffffffff,
        'base_sha256': hashlib.sha256(o).hexdigest(),
        'result_crc32': zlib.crc32(p) & 0xffffffff,
        'os_header': OS_HDR, 'crc_off': CRC_OFF, 'os_size': size,
        'patches': patches,
    }
    js = ('// GENERATED by tools/make_patch.py - do not edit.\n'
          '// Contains only Open500 code (no Akai firmware bytes except the 4-byte hook site it checks).\n'
          'var OPEN500_PATCH = ' + json.dumps(out, indent=1) + ';\n'
          "if (typeof module !== 'undefined') module.exports = OPEN500_PATCH;\n")
    open(os.path.join(ROOT, 'docs', 'patch.js'), 'w').write(js)
    for name, src in ADDONS:
        shutil.copyfile(os.path.join(RE, src), os.path.join(ROOT, 'docs', 'addons', name))
    ours = sum(len(x['data']) // 2 for x in patches)
    print('patch: %d blocks, %d bytes of ours; base crc32 %08x -> result %08x' % (len(patches), ours, out['base_crc32'], out['result_crc32']))
    for x in patches:
        assert set(bytes.fromhex(x['orig'])) <= {0} or x['off'] == 0x2B328, "the patch would overwrite non-zero Akai data @%#x" % x['off']
    print('add-ons copied:', ', '.join(n for n, _ in ADDONS))

if __name__ == '__main__':
    main()
